version: "3.9"
services:
  product-search-service:
    build: ./product-search-app
    ports:
      - "8000:5000"
  product-shipping-service:
    build: ./product-shipping-app
    ports:
      - "9000:5000"
  best-sellers-api:
    build: ./best-sellers-api
    ports:
      - "10000:3000"
  website-app:
    build: ./web-app
    ports:
      - "4000:80"
    volumes:
      - ./web-app/public-html:/usr/local/apache2/htdocs/
